# Generated by Django 4.0 on 2022-01-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vac',
        ),
    ]
